// Script assets have changed for v2.3.0 see
// https://help.yoyogames.com/hc/en-us/articles/360005277377 for more information
function QuincyDialogueManager(name, happiness, happinessMax, drunkenness, drunkennessMax, firstArrival, drink){
	var dialogue = ".";
	var conversation1 = ".";
	// will require dead line at the end of each conversation
	if(!firstArrival){
		dialogue = ["Hm, I think I will have a " + drink + "to start. Yes, definitely a " + drink + ".", "It looks like Rik finally found a helping hand! Splendid, splendid. To reiterate, my name is Quincy, local sell sword and part-time adventurer. I come to Rik's every now and then to sooth my soul.","Now that you're here though I have someone new to engage in conversation with. A pleasant turn of events, indeed.","I could regale you with such tales! My journey across the Broken Crag Cliffs! My duel against the Laughing Swordsman in the Golden Valley! Ah, such stories. Wonderful.","Before any stories though, a very important question for you. Are you a fan of swords?",["I love swords!","I'm an axe person."],["I knew it! You struck me as a sword person through and through. Wonderful, wonderful!","Axes? Never met an axe person before. Interesting. I'm…not sure how to address that."],"Regardless, having you here will help the atmosphere, I'm sure! Also, if I do get drunk, pardon my, um, sleepiness. Alcohol has a tendency to tire me out.","Now then, I’ll take my " + drink + " and be on my way.","."];
	}
	else if(firstArrival)
	{
		if ((happiness >= (happinessMax / 2)) && (drunkennessMax >= (drunkenness / 2))){
			conversation1 = ["Ah, my new friend! I would love to order a " + drink + ".","Now, have I told you the story of my meeting with the Black Knight? Of course, I haven't! Let me begin then.","I was taking a stroll through the Everglow Woods, when out of the corner of my eye I noticed the sheen of black and silver armor! It was the Black Knight.","Our gazes met and I steeled myself for the duel of my life. Back and forth we went, trading physical blows and verbal barbs. Eventually, the fiend had me on the ground, his sword pointed at my head. Dear friend, could you guess what happened next?",["You swept his leg.","He stabbed you."],["Yes! I swept his leg and he crumpled like an empty sack of flour!","No! Do you see a scar on me anywhere? I swept his leg and he crumpled like an empty sack of flour."],"As I stood over the friend, I took a moment to reflect on my victory and realized that I should be merciful. I offered him my hand in lieu of my blade.","He accepted! Now we are friends. His wife is lovely.","Ah, I do love telling a good story. Anyway, if you could pass me my " + drink + ", I'll be on my way.","."];
			dialogue = conversation1;
		}
		// happy and drunk text in text box
		else if ((happiness >= (happinessMax / 2)) && (drunkennessMax <= (drunkenness / 2))){
			conversation1 = ["Ah...*zzzzzzzzzz*...what? Oh, yes...my friend...could I get a *zzzzzzzz* a " + drink + ".","You are doing...well here, my friend. A natural...*zzzzzz*... at your job. I too am a natural......*zzzzzz*....dsman. My teacher Sir Arthur says as much.","Quite the man, Sir Arthur. Legend has it that he....*zzzzzzzzzzzzzzzzz*....and then he....*zzzzzzzzz*... but not before he slayed mighty Ragnorar!","Did you know that he...*zzzzzzzzzz*... and then went and...*zzzzzzzzzzzz*... Quite the feat, no?",["I did know that.","I'm sorry, what?"],["Ah, I should have assumed that Sir Arthur's...*zzzzzz*... had traveled far.","How do you not know of these stories? I am ....*zzzzzz*...."]," Ah, but there are so many more stories of Sir Arthur. Perhaps I will tell....*zzzzzzz*.....later, after my (drink).","."];
			dialogue = conversation1;
		}
		// angry and sober text in text box
		else if ((happiness <= (happinessMax / 2)) && (drunkennessMax >= (drunkenness / 2))){
			conversation1 = ["I would like a " + drink + ", please.","Friend, we must talk. It seems as though your skill in the bartending profession is lacking. Patrons have taken notice, myself included, and I must say that I am disappointed.","But fear not! A rousing story of my travels will encourage you, I am sure. I shall tell you of my meeting with the dragon Pallafor.","Now, as you know, Pallafor is one of the mightiest dragons in the land. His scales are the size of planks of wood, and his fire breath can destroy an entire city in seconds!","So there I was, walking my way through the Mirror Caves, when suddenly Pallafor was before me...wounded.","I walked up and asked him how he acquired such a wound. He informed me that another dragon, Bellafor I believe the name was, had ambushed him and rendered a mighty gash across his chest.","The wound was deep, and Pallafor informed me that he could not recover from it due to Bellafor's poisoned claws. His only chance was to have the wound treated with Elder Root.","I happened to have a large amount of Elder Root on hand! Now, could you guess what I did?",["You treated the wound.","You threw it and ran."],["Yes! Despite the fear that filled me being near such a beast, I went over and treated his wound.","What? No! I am no coward! I went to Pallafor and treated his wounds."],"After treating him, he thanked me and went on his way, leaving a single coin and this story as payment. I hold onto that coin dearly.","I hope this story helps you improve at your work, friend. Now, about my " + drink +"?","."];
			dialogue = conversation1;
		}
		// angry and drunk text in text box
		else if ((happiness <= (happinessMax / 2)) && (drunkennessMax <= (drunkenness / 2))){
			conversation1 = ["Could I....*zzzzzzzzzzzzz*...get a " + drink + "?","Friend, it seems like people...*zzzzzzzzzzzzzzz*... about you. Not good things. Not good things at all.","I must agree ...*zzzzzzzz*... 'em that you are dropping...*zzzzz*...somewhat.","Perhaps a story...*zzzzzz*... guide you along your path.","In the depths of the ....*zzzzzz*... I fought the mighty ....*zzzzzz*..","It was a dangerous battle, filled with.....*zzzzzzzzzzzzzz*.... and ....*zzzzzzzzz*.... and ....*zzzzzzzz*....","Then, when ....*zzzz*.... lay defeated on the ground, he looked at me and said ...*zzzzzzz*.... His words shocked me and I dropped my sword.","Friend, do you understand the meaning of his words?",["Yes.","Uh, no."],["Ah, I knew you would. The lesson is important.","No? The meaning is so obvious. It's as if you didn't hear what I said."],"Regardless, his words resonated with me throughout the Battle of ...*zzzzzz*... but that is a story for a different time. Now, pass me my " + drink + " and I will be on my way.","."];	
			dialogue = conversation1
		}
	}
	return dialogue;
}