// Script assets have changed for v2.3.0 see
// https://help.yoyogames.com/hc/en-us/articles/360005277377 for more information
function RikDialogueManager(name, happiness, happinessMax, drunkenness, drunkennessMax, firstArrival, drink){
	var dialogue = ".";
	var conversation1 = ".";
	var conversation2 = ".";
	var conversation3 = ".";
	// will require dead line at the end of each conversation
	if(!firstArrival){
		dialogue = ["Welcome to your first day at Rik's Rowdy and Raucous Rest Stop and Tavern. People, uh, just usually call it Rik's...anyway, I'm your boss, Rik! I'll be keeping up with you throughout the night, but for now, I will show you the ropes to be a good bartender! Tap the dialogue box to continue.","First things first, let me order a drink. Hmmmm, I think I will have a " + drink + "! Tap the arrow on the left or right to switch to the mixing station, then tap the dialogue box to continue.","Great! This is the mixing station. Here, you will combine different ingredients and mixing techniques to make drinks for customers. Tap the Recipe Scroll on the right to see how to make a " + drink + ", then tap the dialogue box to continue.","Follow the symbols in the mixing station to make the drink. Swipe through the ingredients at the bottom to see everything you have.","To add different ingredients, just tap them when the shaker is open. Depending on the ingredient, you may need to tap them or pinch them once they are above the shaker.","Once everything is added, close the shaker and shake it up! Then add the drink to the correct glass!", "If you followed my instructions correctly, the drink will appear complete on the bar.", "Now you know how to make a " + drink + "! You can start making it now. While making the drink, the customer who ordered will want to keep talking to you, so make sure to keep the conversation moving by tapping the dialogue box.","While waiting for drinks, a customer's happiness (represented by the bar below their character) will decrease. There are two ways to increase happiness: completing drink orders correctly or making correct Choices during conversations.",
		"Oh! I forgot about Choices! Sometimes during conversations, customers may ask about you, for your advice, for your opinion, etc. When that happens, two Choices will appear where the dialogue box is, and you will have to select one.", "Depending on your choice, the character's happiness will increase or decrease. Don't fret if you make the wrong choice though! They may ask you the same thing later. Now, let's practice with Choices.", "What is most important about being a bartender? Pick whichever choice you think is best!", ["Making the best drinks!","Talking with customers!"],["Making the best drinks is very important!","Making friends with customers is super important!"], "However, this was a trick question. Making the best drinks AND making friends with customers are super important! So you best do both!","If you haven't finished making my drink yet, do so now. If you have, tap the dialogue box to continue.","The drink you made me is on the bar now. To give it to me, drag it over to me, and release. Don't do it yet though! I've got a few last things to say.","First off, once you tap a customer, you can only talk to and make the drink for that customer. I like a policy of personal care with my customers.","If you give a customer their drink mid-conversation, you will end the conversation you were having with them. Sometimes that's a good thing to do when you've got a lot of customers, but other times you may want to get as much out of the conversation as possible.", "Also, the more customers drink, the more drunk they get! They'll talk about different things while drunk, maybe some personal things, but just remember to treat them with respect.","Finally, you'll notice in the 'Unsatisfied Customers' in the top left and the 'Satisfied Customers' in the top right.","When a customer's happiness bar is competely depleted, they will become unsatisfied and leave. If enough become unsatisfied and leave, I'll have to shut down for the night. I don't want to to do that.", "BUT, if a customer is happy enough and drunk enough, they become satisfied! And if enough customers become satisfied, then we get to close early on a count of a good night!", "Well, I think that's everything I have to say! Now drag that drink over to me and let’s get to bartending!", "."]
	}
	else if(firstArrival)
	{
		// happy and sober text 
		if ((happiness >= (happinessMax / 2)) && (drunkenness >= (drunkennessMax / 2))){
			//dialogue = ["This is a dialogue test. This line is now longer in order to test how the text wraps. I hope it is wrapping nicely. I am now typing an even longer line to see how far the lines will go down. If this goes over then I have a pretty good idea how far they go.", "Now lets see if the dialogue box location switches when I switch stations.", "Hell yeah, it did!", "Now for branching dialogue.", "A 'yes' and 'no' box should appear to the left and right.", ["Yes, this is a long line.", "No, this is a longer line."], ["Option 1 selected.", "Option 2 selected."], "Wow, you selected an option!", "Let's see if you can do that again.", ["I can.", "I cannot."], ["Nice job!", "You gotta believe in yourself."], "You did it!", "The dialogue test is over."];
			conversation1 = ["Well hey there! Hope the place is treating you well. Sometimes I like to partake of my own stock, haha. I'll have a " + drink + ", please!", "I'm glad you decided to come and work here. I've been short staffed for awhile now and having you here is gonna be a huge help to me.", "What made you want to become a bartender, anyway?", ["I love the work.", "I needed money."], ["Really?! That's great to hear! Now I'm even more happy I hired you.","Ah, well, makes sense. Just make sure you do a good job, okay?"], "Regardless, whatever you do here, just make sure to keep the customers happy, okay? That's the most important thing.", "Ah, people are starting to stare. Maybe it's not a good look for the boss to be drinking on the job. Pass me my drink and I'll be on my way.", "."];
			conversation2 = ["Hey hey, I'm back! Gonna partake of my own stock a bit. Could I get a " + drink + "?","If I haven't said it before, I'm so glad that you're working here. The extra pair of hands is great.","Just maybe, uh, don't do what I'm doing and drink on the job haha. You wouldn't do that, right?", ["Not a chance.","I would if I could."], ["Great! Glad I can trust you.","Well then, looks like I'll have to keep an eye on you."], "You know, running a bar is a crazy experience, let me tell yah. Meeting new people, making new drinks, having a good time all around. It's just a fun experience!", "Are you have a good time here?", ["Yes!","No."], ["I knew you would like it!", "Really? Seems like you picked the wrong job."], "Oh, looks like some people are looking over here. Pass me my drink so I can leave.", "."];
			conversation3 = ["Look at this! You're a natural! Glad you're getting along so well. Now, how about you make me a" + drink + ".","You're a real life saver, you know that? You taking this job really saved my bacon. Without you, this place may have gone under!","But now we're gonna have more people coming in then ever before. I just know it.","You think you’re ready for that when it happens?", ["I definitely am!","Uh, I'm not sure."],["I knew it! I knew you'd be ready! When that day comes, your bartending skills will shine.", "Oh, really? Well, looks like I'll have to do more work to train you later then."], "But yes, more people means more money, and more money means hiring more bartenders. Soon I won't even have to lift a finger!","Just you up front commanding an army of bartenders and me in the back planning out franchises!","o	Well, enough dreaming. I gotta get back to work. Though I do need my drink, so pass it down my way.","."];
			randomize();
			dialogue = choose(conversation1, conversation2, conversation3);		
		}
		// happy and drunk text in text box
		else if ((happiness >= (happinessMax / 2)) && (drunkenness <= (drunkennessMax / 2))){
			conversation1 = ["Well...*hic* if it isn't my favorite...and only employee! Could I get a " + drink + "?", "Gosh kid, you're just...*hic*... a life saver, you know that? It's been rough here without any help...*hic*! Nobody wants to bartend...anymore but you! You do! And you're...*hic* good at it.","You’re drinks are...good. You talk *hic* good. You're the whole damn package! I'm glad I found yah.","Wanted to ask though...bit of a *hic* hard question. Am...*hic*...am I a good boss?",["Yeah, you're great!","Uh, you're fine"],["Great?! Great?!? Great!!! Ah, I'm so...*hic*...happy to hear that!","Just...*hic*...fine? Bah, kids these days"],"Well, either way, you're a darn good employee. Now...*hic* if you could pass me my drink I’ll...be on my way.","."];
			conversation2 = ["Ah...*hic* my favorite employee! Rik needs a" + drink + "!", "You know...*hic*...having you here is just *hic* great. You're a magician behind the counter!","I'm hearing great...*hic*... things from the other customers too. Seems like you're *hic* getting along with them.","You are getting along with them, yeah?", ["Yeah, they're great!","Eh, not really."], ["Wonderful...*hic*! Glad you like the regulars.","Well...*hic*...you best start liking 'em. They'll be 'round *hic* quite a lot."], "Either way, I'm *hic* just glad to have you at the bar. You're doing a hell of a job!", "And hey, keep working like this and...*hic* you may just take over!", "...*hic*... You wouldn't actually take over, right?",["Of course not!","Eh, maybe."],["Oh, good! *hic* I really like this place...*hic* and the name wouldn't make sense...without me!","Oh...*hic*...well I guess I gotta...keep my eye on you."],"Well, whatever. It'll all work out well *hic* in the end! Now if you could bring me my " + drink + ", that'd be great.","."];
			conversation3 = ["*hic*...Hey! It's you! Could I get...a " + drink + ".","Wow...*hic*...you're doing so well! It's like...you've been working here *hic* your whole life!","Couldn't of ask...for a better *hic* bartender than you! I'm really glad you're...here...","Was wondering *hic* how do you like working...here? You having *hic* a good time?",["Yeah, it's great!","Eh, not really."],["Really?!? *hic* That's great to hear! I'm glad you're having a good time.","Oh...*hic*...well...Uhm, I hope things...*hic* get better for yah soon."],"You know, I didn't think this place *hic* would be doing so well when I first opened...but it's really coming together!","Maybe soon I can franchise...that's the dream...*hic*","Anyway, I should get back to...uh...*hic* something. Could you hand me my " + drink + "?","."];
			randomize();
			dialogue = choose(conversation1, conversation2, conversation3);		
		}
		// angry and sober text in text box
		else if ((happiness <= (happinessMax / 2)) && (drunkenness >= (drunkennessMax / 2))){
			conversation1 = ["Hey there! I need to talk to you, could you get me a" + drink + "?","So I've got to say, I'm noticing that you're lacking a bit. Now, I don't want to be too critical, but I think you've got to be more focused.","I know I am not a 'normal' customer. I mean, I'm your boss! But, you gotta treat me, and everyone else, with courtesy and respect.","You think you can do that?",["Absolutely!","Probably not."],["That's great! That's exactly what I want to hear.","Okaaay. Just know that going down that path probably leads to me firing you."],"Anyway, just focus more on work and I'm sure everything will be fine. I really don't want to regret hiring you.","Now, I'll take my " + drink + ", please.","."];
			conversation2 = ["Hey. So we need to talk. Could you make me a " + drink + "?","Look, I'm hearing through the bar that you may be slacking a bit on your duties. Look, I know it's hard to please everyone, and adding myself into the mix may not be the best idea.","But, I've got to keep you on your toes. Everyone in the bar matters, okay?","So I'll ask you; does everyone in the bar matter?",["Absolutely!","Eh, not everyone."],["Great! Glad to hear we are on the same page.","No, everyone does. Even if you don't like someone, you have to treat them right. Hospitality 101."],"Look, I know you can improve, but if you keep making mistakes I can't promise that I can keep you around, okay?","Unless...well, I've never asked. Do you like this job?",["Yeah!","Not really."],["Oh! That's good to hear. Just got to get into the swing of things.","What? Then why did you...never mind."],"Well, I've got to get back to work. Could you hand me my " + drink + "?","."];
			conversation3 = ["Okay, we need to talk. Gotta keep you practicing though, so make me a " + drink +".","Look, I know bartending is hard, but I am seeing you slipping right now. Some people in the bar are talking about it, and I myself am experiencing it.","Once again, I know the job is hard, but you've got to pull it together and keep everyone happy, okay?","Actually, let me ask you something, you think you can handle this job?",["Definitely!","I'm not sure."],["Great! That's the confidence I'm looking for.","Hmmm. Well, I guess time will tell."],"Anyway, I need to get going. Could you hand me my " + drink + "?","."];
			randomize();
			dialogue = choose(conversation1, conversation2, conversation3);	
		}
		// angry and drunk text in text box
		else if ((happiness <= (happinessMax / 2)) && (drunkenness <= (drunkennessMax / 2))){
			conversation1 = ["Hey! *hic* We gotta talk. And make me a " + drink + " while you're at it","Look...*hic* I hired you 'cause...well cause I needed help, but you don't *hic* seem to be helping all that much.","I've got people in the bar talking bad about you and even some people talking bad about *hic* me. Now, we can't have that...alright?","I need to know that I *hic* can trust you behind that counter. So *hic* can I trust you?",["Definitely!","Maybe?"],["*hic* Now THAT is what I want to hear!","*hic* No no no you need to be more confident!"],"Well, anyway, I need *hic* to try and work. Hand me my " + drink + ".","."];
			conversation2 = ["."];
			conversation3 = ["."];
			randomize();
			dialogue = choose(conversation1, conversation2, conversation3);	
		}
	}
	
	return dialogue;
}